CREATE DATABASE IF NOT EXISTS USERS; 
USE USERS;
CREATE TABLE USERS_INFO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USUARIO VARCHAR(150),
    NOMBRE_APELLIDO VARCHAR(150),
    CORREO VARCHAR(150),
    TELEFONO VARCHAR(150),
    DIRECCION VARCHAR(250)    
);
SELECT * FROM USERS_INFO;
ALTER TABLE USERS_INFO ADD ADMIN BIT(1);
ALTER TABLE USERS_INFO MODIFY COLUMN ADMIN BIT;
SELECT * FROM USERS_INFO;
INSERT INTO USERS_INFO (NOMBRE_APELLIDO,CORREO,TELEFONO,DIRECCION,ADMIN) VALUES ("MARIMAR","maria@gmail.com","+1144448888","LAVALLE 1000",1);
INSERT INTO USERS_INFO (USUARIO,NOMBRE_APELLIDO,CORREO,TELEFONO,DIRECCION) VALUES ("LEO","LEONARDO ROJAS","leo@gmail.com","+1155558888","CORRIENTES 1000");
UPDATE USERS_INFO SET ADMIN=0 WHERE ID=2

