CREATE DATABASE IF NOT EXISTS USERS; 
USE USERS;
CREATE TABLE USERS_INFO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USUARIO VARCHAR(150),
    NOMBRE_APELLIDO VARCHAR(150),
    CORREO VARCHAR(150),
    TELEFONO VARCHAR(150),
    DIRECCION VARCHAR(250),
    ADMIN BOOL,
    PASSWORD VARCHAR(100)
);
SELECT * FROM USERS_INFO;
 SELECT * FROM USERS_INFO WHERE USUARIO='LEN'
ALTER TABLE USERS_INFO ADD PASSWORD VARCHAR(100);
ALTER TABLE USERS_INFO MODIFY COLUMN ADMIN BOOL;
SELECT * FROM USERS_INFO WHERE CORREO='leo@gmail.com';
INSERT INTO USERS_INFO (NOMBRE_APELLIDO,CORREO,TELEFONO,DIRECCION,ADMIN) VALUES ("MARIMAR","maria@gmail.com","+1144448888","LAVALLE 1000",1);
INSERT INTO USERS_INFO (USUARIO,NOMBRE_APELLIDO,CORREO,TELEFONO,DIRECCION) VALUES ("LEO","LEONARDO ROJAS","leo@gmail.com","+1155558888","CORRIENTES 1000");
UPDATE USERS_INFO SET PASSWORD='123456INIT' WHERE ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14)

CREATE TABLE PRODUCTS_INFO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME_PRODUCT VARCHAR(150) NOT NULL,
    PRICE_PRODUCT INT(5) NOT NULL,
    IMAGE_PRODUCT VARCHAR(450) NOT NULL 
);
SELECT * FROM PRODUCTS_INFO;
ALTER TABLE PRODUCTS_INFO MODIFY COLUMN IMAGE_PRODUCT VARCHAR(450) NOT NULL;
INSERT INTO PRODUCTS_INFO (NAME_PRODUCT, PRICE_PRODUCT, IMAGE_PRODUCT) VALUES ("Veggie Avocado", "310", "https://cdn.loveandlemons.com/wp-content/uploads/2016/05/IMG_2016_05_16_07916-cropped.jpg");
INSERT INTO PRODUCTS_INFO (NAME_PRODUCT, PRICE_PRODUCT, IMAGE_PRODUCT) VALUES ("Bagel de Salmon", "425", "https://kathrynskitchenblog.com/wp-content/uploads/2018/05/SmokedSalmonBagel5.jpg");

CREATE TABLE ORDERS_INFO(
	NUMERO INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO VARCHAR(150) NOT NULL,
    HORA VARCHAR(150) NOT NULL,
    DESCRIPCION VARCHAR(350) NOT NULL, 
    PAGO_TIPO VARCHAR(150) NOT NULL,
    PAGO_MONTO VARCHAR(150) NOT NULL,
    USUARIO VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL
);
SELECT * FROM ORDERS_INFO;
SELECT * FROM ORDERS_PRODUCTS
UPDATE ORDERS_INFO SET DESCRIPCION=CONCAT(DESCRIPCION, ' hola'),PAGO_MONTO= PAGO_MONTO + 6, HORA='20:33:00' WHERE NUMERO=1;
UPDATE ORDERS_INFO SET PAGO_MONTO= PAGO_MONTO + 6 WHERE NUMERO=1;
DELETE FROM ORDERS_INFO WHERE NUMERO =67;
DELETE FROM ORDERS_PRODUCTS WHERE ID IN (16,17);
ALTER TABLE ORDERS_INFO MODIFY COLUMN  DESCRIPCION VARCHAR(350);
INSERT INTO ORDERS_INFO (ESTADO,HORA,DESCRIPCION,PAGO_TIPO,PAGO_MONTO,USUARIO,DIRECCION) VALUES ("NUEVO",CURTIME(),"1xHamClass 1xSandVegg","Efectivo","$660","MARIMAR","LAVALLE 1000");
INSERT INTO ORDERS_INFO (ESTADO,HORA,DESCRIPCION,PAGO_TIPO,PAGO_MONTO,USUARIO,DIRECCION) VALUES ("CONFIRMADO",CURTIME(),"2xHamClass 6xCerSLATA 1xVerde","Credito","$2520","LEO","CORRIENTES 1000");

UPDATE PRODUCTS_INFO SET NAME_PRODUCT='Sandwich',PRICE_PRODUCT=6,IMAGE_PRODUCT='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdE_GLogtSf2sEna7RAXMZTYCoddxolbH1qw&usqp=CAU' WHERE ID=4;
SELECT TELEFONO FROM USERS_INFO WHERE USUARIO=MARIMAR;

CREATE TABLE ORDERS_PRODUCTS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORDER INT NOT NULL,
	ID_PRODUCT INT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    AMOUNT_PRODUCT INT NOT NULL,
    PRICE_PRODUCT INT NOT NULL
);
SELECT * FROM ORDERS_PRODUCTS
ALTER TABLE ORDERS_PRODUCTS ADD PRODUCT_NAME VARCHAR(100);
ALTER TABLE ORDERS_PRODUCTS MODIFY COLUMN  PRODUCT_NAME VARCHAR(100) NOT NULL;
DROP TABLE ORDERS_PRODUCTS
DELETE FROM ORDERS_PRODUCTS WHERE ID IN (4);
